# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"



gem "ruby2d", "~> 0.9.4"

gem "tty-prompt", "~> 0.21.0"

gem "faker", "~> 2.11"

gem "colorize", "~> 0.8.1"
